// Code generated by MockGen. DO NOT EDIT.
// Source: plan.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/alexanderramin/kalistheniks/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// GetLastSession mocks base method.
func (m *MockSessionRepository) GetLastSession(ctx context.Context, userID string) (models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSession", ctx, userID)
	ret0, _ := ret[0].(models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastSession indicates an expected call of GetLastSession.
func (mr *MockSessionRepositoryMockRecorder) GetLastSession(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSession", reflect.TypeOf((*MockSessionRepository)(nil).GetLastSession), ctx, userID)
}

// GetLastSet mocks base method.
func (m *MockSessionRepository) GetLastSet(ctx context.Context, userID string) (models.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSet", ctx, userID)
	ret0, _ := ret[0].(models.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastSet indicates an expected call of GetLastSet.
func (mr *MockSessionRepositoryMockRecorder) GetLastSet(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSet", reflect.TypeOf((*MockSessionRepository)(nil).GetLastSet), ctx, userID)
}
