// Code generated by MockGen. DO NOT EDIT.
// Source: sessions.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/alexanderramin/kalistheniks/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// AddSet mocks base method.
func (m *MockSessionRepository) AddSet(ctx context.Context, set *models.Set) (*models.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSet", ctx, set)
	ret0, _ := ret[0].(*models.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSet indicates an expected call of AddSet.
func (mr *MockSessionRepositoryMockRecorder) AddSet(ctx, set interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSet", reflect.TypeOf((*MockSessionRepository)(nil).AddSet), ctx, set)
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, s *models.Session) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, s)
}

// ListWithSets mocks base method.
func (m *MockSessionRepository) ListWithSets(ctx context.Context, userID *uuid.UUID) ([]*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithSets", ctx, userID)
	ret0, _ := ret[0].([]*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithSets indicates an expected call of ListWithSets.
func (mr *MockSessionRepositoryMockRecorder) ListWithSets(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithSets", reflect.TypeOf((*MockSessionRepository)(nil).ListWithSets), ctx, userID)
}

// SessionBelongsToUser mocks base method.
func (m *MockSessionRepository) SessionBelongsToUser(ctx context.Context, sessionID, userID *uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionBelongsToUser", ctx, sessionID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionBelongsToUser indicates an expected call of SessionBelongsToUser.
func (mr *MockSessionRepositoryMockRecorder) SessionBelongsToUser(ctx, sessionID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionBelongsToUser", reflect.TypeOf((*MockSessionRepository)(nil).SessionBelongsToUser), ctx, sessionID, userID)
}
